version: '3.7'

volumes:
  wpDbData:
networks:
  wpNetwork:

services:
  # DB Service
  db:
    image: mysql:5.7
    volumes:
      - wpDbData:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: a12345
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    ports:
      - 8889:3306
    restart: always
    networks:
      - wpNetwork
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      PMA_HOST: db
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: a12345
    ports:
      - 8081:80
    restart: always
    networks:
      - wpNetwork
  # wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8080:80
      - 443:443
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
    volumes: ['./:/var/www/html']
    networks:
      - wpNetwork
    container_name: wordpress-site
